pipeline:
  image: platform/go:1.15
  stages:
    "Build Binary":
      cache:
        - path: /gopath
      env:
        GOPATH: /gopath
        CGO_ENABLED: 0
        GOOS: linux
      steps:
        - |
          go mod download
          go build \
            -ldflags "-s -w -X github.com/weaveworks/flagger/pkg/version.REVISION={{ codebase.revisionId }}" \
            -a -installsuffix cgo -o bin/flagger ./cmd/flagger/*.go
    
    "Build Docker Image":
      imageBuild: &imageBuild
        push: true
        tags:
          - 1.1.0.pes1.0-1

    "Deploy Docker Image":
      branch: master
      imageBuild:
        <<: *imageBuild
        push: true
        